// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalR.EFModels;

#nullable disable

namespace SignalR.Migrations
{
    [DbContext(typeof(SignalrContext))]
    [Migration("20240914003420_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SignalR.EFModels.Connections", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignalrId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Connecti__3214EC0773C23469");

                    b.HasIndex("PersonId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("SignalR.EFModels.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Person__3214EC072C15C01C");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("SignalR.EFModels.Connections", b =>
                {
                    b.HasOne("SignalR.EFModels.Person", "Person")
                        .WithMany("Connections")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK__Connectio__Perso__398D8EEE");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SignalR.EFModels.Person", b =>
                {
                    b.Navigation("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
